test_1a_register (__main__.GSChrome) ... ok
test_1b_login (__main__.GSChrome) ... ok
test_2a_mount_container (__main__.GSChrome) ... ok
test_2b_disconnect_container (__main__.GSChrome) ... ok
test_3_setting_up (__main__.GSChrome) ... ERROR
test_4a_import_url (__main__.GSChrome) ... skipped 'Skipped for failed to prepare importing file using public URL test.'
test_4b_upload_file (__main__.GSChrome) ... skipped 'Skipped for failed to prepare uploading test.'
test_5a_generate_public_URL (__main__.GSChrome) ... skipped 'Skipped for failed to prepare generating public URL test.'
test_6a_change_file_name (__main__.GSChrome) ... skipped 'Skipped for failed to prepare renaming test.'
test_6b_copy_data_btw_folders (__main__.GSChrome) ... skipped 'Skipped for failed to prepare subdirs'
test_6c_copy_data_btw_containers (__main__.GSChrome) ... skipped 'Skipped for failed to prepare subdir1'
test_6d_delete_file (__main__.GSChrome) ... ERROR
test_6e_move_data_btw_folders (__main__.GSChrome) ... skipped 'Skipped for failed to prepare subdirs'
test_6f_move_data_btw_containers (__main__.GSChrome) ... skipped 'Skipped for failed to prepare subdir1'
test_7b_launch_with_file (__main__.GSChrome) ... skipped 'Skipped for failed to prepare launch Galaxy with file test.'
test_8_get_DOI (__main__.GSChrome) ... ERROR

======================================================================
ERROR: test_3_setting_up (__main__.GSChrome)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Regina/Documents/VLSCI_MAC_Documents/UROP/SeleniumTesting/data_test_preparation.py", line 240, in test_3_setting_up
    self.files()
  File "/Users/Regina/Documents/VLSCI_MAC_Documents/UROP/SeleniumTesting/data_test_preparation.py", line 227, in files
    raise PreparationException(report)
PreparationException: Failed to prepare for the file tests.
PreparationException: Failed to prepare for the file tests.
Failed to delete the existing file_to_upload.txt.
PreparationException: Failed to prepare for the file tests.
Failed to delete the existing after_rename.txt.
PreparationException: Failed to prepare for the file tests.
Failed to delete the existing file_for_pURL.txt.
PreparationException: Failed to prepare for the file tests.
Failed to delete the existing file_to_copy.txt.
PreparationException: Failed to prepare for the file tests.
Failed to delete the existing file_to_move1.txt.
PreparationException: Failed to prepare for the file tests.
Failed to delete the existing file_to_delete.txt.
PreparationException: Failed to prepare for the file tests.
Failed to delete the existing file_to_publish.txt.
PreparationException: Failed to prepare for the file tests.
Failed to delete the existing file_for_pURL.txt.
PreparationException: Failed to prepare for the file tests.
Failed to delete the existing file_to_launch_GVL_with.txt.


======================================================================
ERROR: test_6d_delete_file (__main__.GSChrome)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Regina/Documents/VLSCI_MAC_Documents/UROP/SeleniumTesting/data_manipulation.py", line 132, in test_6d_delete_file
    elif not GST.deleting_data_test_ready:
AttributeError: type object 'GenomeSpaceTest' has no attribute 'deleting_data_test_ready'

======================================================================
ERROR: test_8_get_DOI (__main__.GSChrome)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Regina/Documents/VLSCI_MAC_Documents/UROP/SeleniumTesting/file_publish.py", line 34, in test_8_get_DOI
    if not GST.publishing_file_test_ready:
AttributeError: type object 'GenomeSpaceTest' has no attribute 'publishing_file_test_ready'

----------------------------------------------------------------------
Ran 16 tests in 81.401s

FAILED (errors=3, skipped=9)
